import Head from 'next/head';
import SimpleCentered from '../components/sections/Hero/SimpleCentered';

export default function Home() {
  return (
    <>
      <Head>
        <title>Mobiland - Landing Page Main</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* Hero section with Navigation */}
        <SimpleCentered />
      </main>
    </>
  )
}
