import Head from 'next/head';
import SimpleCentered from '../components/sections/Hero/SimpleCentered';
import CenteredNavbar from '../components/common/Navbar/CenteredNavbar';
import DarkWithIllustration from "../components/sections/Hero/DarkWithIllustration";

export default function Home() {
  return (
    <>
      <Head>
        <title>Mobiland - Landing Page Main</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-lotion">
        <CenteredNavbar />
        {/* Hero section with Navigation */}
        <DarkWithIllustration />
        {/* <SimpleCentered /> */}
      </main>
    </>
  )
}
